name: CI (Alt)

on:
  workflow_dispatch:
    inputs:
      ROM_LINK:
        description: "Direct Link of ROM/Firmware"
        required: true
        default: 'https://android.googleapis.com/packages/ota-api/package/bb874810656ab780de64da121f1d23ea38c80bce.zip'
env:
  ROM_LINK: ${{ github.event.inputs.ROM_LINK }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  GIT_ORG: "AndroidFW"
  CHAT_ID: ${{ secrets.CHAT_ID }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

jobs:
  dump:
    runs-on: depot-ubuntu-24.04-8

    steps:
      - name: Dump Firmware
        run: |
          set -ex
          export TERM=xterm
          git clone -q --depth=1 https://github.com/EduardoA3677/DumprX.git rom
          cd rom
          bash ./setup.sh || exit 1
          sudo apt-get update
          sudo apt-get install neofetch cpio aria2 lz4 gzip yt-dlp xz-utils lzma zstd curl wget file lzop coreutils openssh-client -qy
          echo "$GITLAB_TOKEN" > .gitlab_token
          echo "$GIT_ORG" > .gitlab_group
          echo "$TG_TOKEN" > .tg_token
          echo "$CHAT_ID" > .tg_chat
          git config --global user.name "EduardoA3677"
          git config --global user.email "ealvarado261500@gmail.com"
          mkdir -p ~/.ssh
          echo "Host gitlab.com" >> ~/.ssh/config
          echo "  User git" >> ~/.ssh/config
          echo "  PreferredAuthentications publickey" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          echo "  TCPKeepAlive yes" >> ~/.ssh/config
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/config
          chmod 600 ~/.ssh/id_rsa 
          chmod 700 ~/.ssh
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh -T git@gitlab.com || true
          yt-dlp -o rom.zip "${ROM_LINK}"
          bash ./dumper.sh rom.zip  || exit 1
